name: my_portfolio
description: "Personal Portfolio"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  bloc: ^9.2.1
  carousel_slider: ^5.1.2
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.3.0
  go_router: ^17.2.3
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  share_plus: ^13.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/shalehi/
    - assets/images/hirsto/
    - assets/images/chalets_admin_booking/
    - assets/icons/
    - assets/pdf/
    - assets/images/salons/
    - assets/images/resturants/
    - assets/images/cars_show_room/
    - assets/images/tablet_catalog/
